### ISSUE TITLE
improvement about excluding controls to be localized from storyboards

### ISSUE THREAD

**Issue by rockingdice** [Flinesoft/BartyCrouch#103]
I've been using this project for months, basically it's working like a charm.
What I thought that it's not quite convenient of the 'excluded mechanism' for the localization of ui controls.

In my project there are a lot of controls that their contents should be dynamically changed. After I've finished the storyboard building, I have to mark most of them to be excluded from generating localized keys by '#bc-ignore!'.

So I think if there's a way to do it oppositely. 
It's likely to have another argument '-w' or whatever, and if it's provided, only the controls with '#bc-include' will be exported to localized strings, else they won't be exported.

Looking forward to your opinion, thanks.

**Comment by rockingdice** [comment]
@Dschee Thanks for your reply.

Currently I'm using a dirty solution to do it, because I'm not very familiar with swift. 

I cannot provide a better way to make a pr for it, sorry =(

**Comment by Dschee** [comment]
Sorry for the late response. Having read the requested feature again, I don't feel like it's a good idea to have a localized Storyboard where most of the elements are dynamic. You should rather not localize the Storyboard then in my opinion. This way you would only add a few more outlets and set the few elements' localizations in Code as well.

But again, that doesn't mean I'm totally against adding this feature. But as I don't see much benefit in it personally, I'd need someone to vulonteer in implementing it. Is there anyone who would want to add this? I'm closing this for now due to inactivity. Will reopen if others are interested in this as well.
