### ISSUE TITLE
String in Localizable.string is wrong while string has some "%".

### ISSUE THREAD

**Issue by EdwardSun123** [Flinesoft/BartyCrouch#104]
If I write code 
'''
let string = NSLocalizedString("%A%B%C", comment: "test")
'''
in project.

There's 
'''
/* test */
"%A%B%C" = "%1$A%2$B%3$C";
'''

in my  Localizable.string.

How to delete string in middle of the copy string, just like "1$","2$"

**Comment by Dschee** [comment]
I'm not sure if you're aware of this and if this is an issue with BartyCrouch, but when you want to place a `%` character into the value side of an `NSLocalizedString`, you need to escape the `%` character by another `%` character, leading you to this:
```
/* test */
"%A%B%C" = "%%A%%B%%C";
```

Since you say this is generated automatically by BartyCrouch, it seems you are using the `default-to-keys` (`-k`) option. BartyCrouch though is simply using Apples tools internally to generate the Strings files contents, so I didn't even know this would happen when the `-k` option is activated and you have `%` characters in the key. But it seems so.

Now I'm not sure if we should implement a feature that prevents this from happening. Some people might expect this to be exactly like this in order to use the `String(withFormat:)` feature to replace placeholders in the translated value (like described [here](https://nshipster.com/nslocalizedstring/) or [there](https://www.objc.io/issues/9-strings/string-localization/#localized-format-strings)).

In any case, I think for now the easiest way for you to fix the issue is probably to use `%%` in the future when you want to place a `%` character in localizations.

**Comment by EdwardSun123** [comment]
Thanks for your reply.
I use lot of "%" because I want to display some percent. Just like  "more than %55 or less than %98".

**Comment by EdwardSun123** [comment]
Thanks for your reply.
I use a lot of "%"  because I need to display some percent just like "more than 20% or less than 80%".
"%%" can not fix it I think.
code 
`let string = NSLocalizedString("more than 23% or less than 45%", comment: "test")`
then 
`/* test */`
`"more than 23% or less than 45%" = "more than 23%1$ or less than 45%2$";`

I think I need more solution.

**Comment by EdwardSun123** [comment]
I used "default-to-keys" (-k) option.
If I use %%
result is 
`let string = NSLocalizedString("more than 23%% or less than 45%%", comment: "test")`

```
/* test */
"more than 23%% or less than 45%%" = "more than 23%% or less than 45%%";
```

It still double% in my UIlabel

**Comment by Dschee** [comment]
Okay, let me investigate this then ...

**Comment by Dschee** [comment]
@EdwardSun123 Thank you for reporting this issue. I had a look and found the issue: While it is true that `%%` is the correct way to use a String with format (through `NSString`), when using plain Strings in Swift you can use a single `%` which is valid. Thus when placing `%%` in the String, the result in the user interface is also `%%`.

While this is an issue with `genstrings` and `extractLocStrings` (tools from Apple) I added a regex which fixes this issue if the value side does not include a valid placeholder. Valid placeholders are for examples:

- `%@`
- `%d`
- `%f`
- `%.2f`
- `%lu`
- `%llo`

Those will not be fixed, so in those cases the value will be kept with those `%1$@` for example. But both of your examples from above should now be fixed and working. I actually used them as test examples, see [here](https://github.com/Flinesoft/BartyCrouch/blob/stable/Tests/Code/StringsFileUpdaterTests.swift#L151), to ensure they don't break in the future.
