### ISSUE TITLE
CocoaPods.org delivers old version

### ISSUE THREAD

**Issue by patricks** [Flinesoft/BartyCrouch#118]
Currently if I install BartyCrouch via CocoaPods.org I get version 3.13.0. Please update it to version 4.0.0.

**Comment by Dschee** [comment]
I remember answering this, but it seems I haven't sent the response. 😞 

Anyways, what I basically wrote was that @Econa77 had added support for CocoaPods and since I neither ever used the CocoaPods version nor know how it is properly integrated, I'd rather let @Econa77 (os someone else) have a look at re-adding support again.

Please note that the reason why I removed it was that I needed to change the contents of the Makefile for adding support for installation via SwiftPM and Mint and didn't know how I could merge the contents properly (I'm not a Makefile master).
