### ISSUE TITLE
is BartyCrouch dead in cocoa pod ? 

### ISSUE THREAD

**Issue by fadizant** [Flinesoft/BartyCrouch#125]
I try to use BartyCrouch using cocoa pod with version 3.13.0 but when I try to install it using 
`brew install bartycrouch`
I got version 4.0 that not support for cocoa pod 

so how can I get the versions 3.13.0 

Thanks.

**Comment by fadizant** [comment]
version 3.13.0 support objective C that's why I have to use it

**Comment by fadizant** [comment]
I found the way that I can use the old one by using 
`brew switch bartycrouch 3.13.1`
in terminal with the old files

**Comment by Dschee** [comment]
Version 4 of BartyCrouch also supports Objective-C, nothing changed in that regard. There's only a new option named `transform` available to Swift only, but the `code` option is still turned on in the default configuration and should still work with Objective-C code, just as in version 3.13.

Also I'm very confused now, since you are installing BartyCrouch via Homebrew, so it's already installed. What does CocoaPods then have to do with it at all? In version 3 we had support for installation of BartyCrouch via CocoaPods (which was dropped in version 4 for the moment), but since you already install it via Homebrew, I don't think there's any need for CocoaPods.

Also please note that some things changed in version 4, that might be the reason why BartyCrouch wasn't working for you immediately. Please see the appropriate section in the [Migration Guide](https://github.com/Flinesoft/BartyCrouch/blob/stable/MIGRATION_GUIDES.md#upgrade-from-3x-to-4x) to migrate from version 3 to 4.

**Comment by fadizant** [comment]
I will Thanks.

**Comment by Dschee** [comment]
Thanks to the help of @djbe this is now fixed and installation via CocoaPods should work again.
