### ISSUE TITLE
Crashes with 'Range or index out of bounds'

### ISSUE THREAD

**Issue by Gutty1** [Flinesoft/BartyCrouch#18]
I have 11 languages in my project and I added the bartycrouch to my build phases and get the following error when building:
BartyCrouch: Successfully updated strings file(s) of Storyboard or XIB file.
2016-06-21 15:04:01.669 genstrings[26695:5181041] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString characterAtIndex:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff93f904f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8f111f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff93ff74bd +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff93f05cf6 -[__NSCFString characterAtIndex:] + 102
	4   genstrings                          0x0000000104d3296b genstrings + 10603
	5   genstrings                          0x0000000104d318d1 genstrings + 6353
	6   genstrings                          0x0000000104d3150c genstrings + 5388
	7   libdyld.dylib                       0x00007fff882125ad start + 1
	8   ???                                 0x000000000000024f 0x0 + 591
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Error! Could not extract strings from Code in directory '/Users/Arie/Developer/multilock-ios'.
Command /bin/sh failed with exit code 69

Please help

**Comment by Dschee** [comment]
Hello @Gutty1, thank you for reporting your issue. Unfortunately the information given don't help me to understand the issue. Could you please provide me with the following information addition information:

– the version of Xcode you are using
– the version of BartyCrouch you have installed (check via `brew list --versions`)

Could you also please try to find the localization key or value that causes this issue? Try it like this:

– create new Xcode project
– configure the BartyCrouch build script within the project
– copy some of your Code files / Interface files one by one to the project and build
– once the file that causes this issue is found, remove all other files
– remove lines / interface elements until the key/translation that causes this issue is found

Alternatively, if your project is open source you can just send me a link to it and I'll have a look. If you are okay with sending me a non-open-source project or the related parts of it, that's okay for me too, of course. Send them to github@dschee.com in that case.

**Comment by Dschee** [comment]
Hey @Gutty1, can you please provide more information on this or is this issue fixed for you?

I really can't do anything about this without more information ... 😞

**Comment by Gutty1** [comment]
hey mate, sorry for the delay, I was OOO

I succeeded to find the problematic string, thank you

Thanks,
 
Arie Guttman

Mobile: +972 (54) 778 2569
P Please consider the environment - do you really need to print this email?

**Comment by Dschee** [comment]
As this problem is solved for you I will close the issue. But it would be great to know what the issue was in the first place so we can prevent it in the future. So, would be great to hear some details, if you mind. 👍

**Comment by Gutty1** [comment]
Sure,
I use define's in an h file for all localizations 
One of the define had by copy/paste mistake a missing closing ')' and the ')' was in the m file, so it compiled without problem but crashed the tool


Thanks & regards
Arie Guttman

Mobile: +972 (54) 7782569

Please consider the environment - do you really need to print this email?
