### ISSUE TITLE
Failed to Install on macOS Sierra

### ISSUE THREAD

**Issue by puelocesar** [Flinesoft/BartyCrouch#35]
Relevant error:
xcodebuild: error: invalid option '-O'

More information about the failed installation:
https://gist.github.com/anonymous/94d069976cd75423c6d0bd6da84e8927

**Comment by puelocesar** [comment]
Sorry, just saw I need to download and install Xcode 7

**Comment by ctn888** [comment]
Hi, were you able to install?  I can't install either because of the same error:
xcodebuild: error: invalid option '-O'

Here's my gist-logs:
https://gist.github.com/957a6b40ed34d01ba62158a2e3191a4b

Running 10.11.6 with Xcode 8 installed.

Running "xcode-select --install" returns:
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

Thanks

**Comment by puelocesar** [comment]
I'm downloading Xcode 7.3 from here: https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_7.3.1/Xcode_7.3.1.dmg

After it's done, I'm planing in running xcode-select and trying to install Bartycroush again

**Comment by Dschee** [comment]
When Xcode 7 is installed you can choose the command line tools from its Settings, see this image:

![bildschirmfoto 2016-09-30 um 10 58 52](https://cloud.githubusercontent.com/assets/6942160/18986410/ef7345f0-86fc-11e6-9d43-4475b94d9535.png)

I'm closing this issue since there is #33 for the Xcode 8 / Swift 3 compatibility issue and this doesn't seem to be a macOS Sierra specific problem. If it turns out to be, I'll reopen, of course.

**Comment by puelocesar** [comment]
It didn't work out:

MacBook-Pro:Desktop paulo$ brew install flinesoft/bartycrouch/bartycrouch
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
p11-kit
==> Updated Formulae
anjuta                at-spi2-core          c-ares                crystal-lang          gitg                  gspell                gxml                  libcouchbase          pgroonga            
at-spi2-atk           brew-gem              ccache                gdl                   glib                  gtksourceview3        kotlin                libgit2-glib          rust                

Error: Your Xcode (7.3.1) is outdated
Please update to Xcode 8.0.
Xcode can be updated from the App Store.

**Comment by puelocesar** [comment]
Apparently, if you upgraded to Sierra, it's impossible to install bartycrouch.. http://discourse.brew.sh/t/brew-now-requires-xcode-8-0/114/11

Now I feel good about not migrating our main project to Swift :P

**Comment by seyfeddin** [comment]
Will there be a fix soon?

**Comment by Dschee** [comment]
There's now a fix in place for the Swift 3 implementation. Just upgrade / install BartyCrouch as described in the README and it should work! See #33 for more details.

**Comment by ctn888** [comment]
Thanks, I was able to install.
