### ISSUE TITLE
Localizing Info.plist

### ISSUE THREAD

**Issue by moray95** [Flinesoft/BartyCrouch#51]
Hello,

Is it possible to use BartyCrouch in order to localize the Info.plist file?
If not, do you have any plan to support this?

**Comment by Dschee** [comment]
You mean your are localizing your Info.plist using Base-Localization having a `Info.plist` file under Base.lproj and multiple `Info.strings` files under your language codes? Well, to be honest, until now I have not added any string extraction feature (both code and Storyboards are supported by Apple command line tools). But since the Info.plist is an XML file it should be possible.

You probably wouldn't want to translate all values though, only some. How would we know which once to localize? Maybe add something like `#bc-localize!` similar to `#bc-ignore!`?

Another question: Do the number of localized fields change often? If not, than I think doing the changes by hand shouldn't bee too much of a horror. At least not as much as it was with Code and Interface Builder files before BartyCrouch existed. ^^

**Comment by moray95** [comment]
Yes, I am in fact using an `InfoPlist.strings` file under my localizations. You are right that there are not a lot of strings to localize and they do not change very often. However, I would much likely appreciate such a tool just to make sure everything is up to date.

**Comment by Dschee** [comment]
I'm all okay with this feature but since it doesn't solve a big problem I'm very unlikely to ever have the spare time to implement it. I'd be happy to merge a good Pull Request with such a feature though. I think the biggest part would be to extract the strings to be localized from within the plist file.

**Comment by Dschee** [comment]
Also note that there are many apps (e.g. [Linguan](https://itunes.apple.com/de/app/linguan/id477163052?mt=12)) that give you an overview of all your translations and let you update them easily. BartyCrouch is only here to make sure new keys are added from files that change often. I think you can find yourself a nice and simple solution for the Info.plist file using one of those tools.

**Comment by Dschee** [comment]
After having a second thought on this I consider this out of scope of BartyCrouch's features. See my previous comments for rationale.
