### ISSUE TITLE
[NSString localizedUserNotificationStringForKey:key arguments:arguments] not found

### ISSUE THREAD

**Issue by SandraK82** [Flinesoft/BartyCrouch#74]
While using UNUserNotifications and the proposed Method of using [NSString localizedUserNotificationStringForKey:key arguments:arguments] for building notifications, I discovered that bartycrouch does not recognize those localisations and thus removes them from my Localizable.strings files.

**Comment by Dschee** [comment]
BartyCrouch simply uses the Apple tool `genstrings` to extract Strings from Code by default. You can try the newer tool `extractLocStrings` by specifying the command option `-e` on the code command, maybe that helps. See [the docs](https://github.com/Flinesoft/BartyCrouch#extractlocstrings-aka--e---extract-loc-strings-optional) for more details. If that doesn't help, then I guess it'll be hard to fix this unless somebody does the work of parsing this case manually. But I suggest you try the above mentioned option first.

**Comment by SandraK82** [comment]
looks like there is currently no support by apple, or at least I could not find any documentation for it

**Comment by Dschee** [comment]
Well then, I'm closing this as we can't fix the issue here without restructuring the entire tool.

Please note though, that there's the [`additive` option](https://github.com/Flinesoft/BartyCrouch#additive-aka--a---additive-optional) on the code sub command which ensures to not delete anything from your Localizable.strings. Instead it will only add new keys and not touch any existing ones. Maybe that will be a compromise you can live with?
