### ISSUE TITLE
Support for Swift Package Manager?

### ISSUE THREAD

**Issue by mshibanami** [Flinesoft/BartyCrouch#82]
I want to manage BartyCrouch with [Mint](https://github.com/yonaskolb/Mint).
It needs SPM support for these commands. 
But BartyCrouch doesn't support it.

Does BartyCrouch have a plan to support SPM?

**Comment by Dschee** [comment]
I definitely want to support SPM!

Until now, it didn't seem like anybody is using SPM for iOS development. But with Mint, things might change. So it makes sense to add support now. Would you like to tackle it yourself, @mshibanami ?

Otherwise, I'll add it to my TODO list and you might need to wait a few weeks since the list is quite full. ^^

**Comment by mshibanami** [comment]
Sure, thanks!
I'll send a pull request soon.
