### ISSUE TITLE
CocoaPods spec is out of date

### ISSUE THREAD

**Issue by foreignfilm** [Flinesoft/BartyCrouch#86]
I see that the latest release of BartyCrouch is [3.10.0](https://github.com/Flinesoft/BartyCrouch/releases/tag/3.10.0), whereas the only available version of the BartyCrouch pod is [3.8.1](https://github.com/CocoaPods/Specs/tree/master/Specs/a/9/d/BartyCrouch). I'm integrating BartyCrouch via Cocoapods and I would like to have access to the latest version to bring in some of the recent bugfixes.

**Comment by Dschee** [comment]
Thanks for the issue. Problem is, I never intended to add CocoaPods support to BartyCrouch, it was done by @Econa77 and I just ran `pod trunk push` to release a CocoaPods version. The problem is, that when I try this now I get an `- ERROR | [OSX] unknown: Encountered an unknown error`.

If someone fixes the issue, I'm happy to do a new upload.

**Comment by crazytonyli** [comment]
I'm guessing it's because portable_bartycrouch.zip file, which can be generated via `make portable_zip`, is missing from recent release product, the only version that has this file is [3.8.1](https://github.com/Flinesoft/BartyCrouch/releases/tag/3.8.1), which is the version in Cocoapods spec repo.

**Comment by Dschee** [comment]
@crazytonyli I just ran the suggested command and uploaded the result as part of the release. Thank you for pointing that out. We should probably automize the release process sometime through a CI server. I also just ran "pod trunk push" which was successful. That should fix this issue. Tell me if not.
