### ISSUE TITLE
Localization strings does not updated

### ISSUE THREAD

**Issue by fadizant** [Flinesoft/BartyCrouch#90]
all nibs updated but I want to update Localizable.strings
`if which bartycrouch > /dev/null; then
    # Incrementally update all Storyboards/XIBs strings files
    bartycrouch interfaces -p "$PROJECT_DIR"

    # Add new keys to Localizable.strings files from NSLocalizedString in code
    bartycrouch code -p "$PROJECT_DIR" -l "$PROJECT_DIR" -a -s
else
    echo "warning: BartyCrouch not installed, download it from https://github.com/Flinesoft/BartyCrouch"
fi`

I have Localizable.strings in my project but it's seems can't find Localizable.strings file 
I got this message 
`Error! No localizations extracted from Code in directory '/Users/jord/Desktop/Test/test'.`

any advice please.

**Comment by fadizant** [comment]
I forget build project to update 
every thing work now thanks :)

**Comment by Dschee** [comment]
Can you provide a demo project, please? Also, which version of BartyCrouch are you using?

**Comment by Dschee** [comment]
Ahh, now that I have looked at this in more detail, note that the error explicitly states that it couldn't extract any localizations from Code, which could simply be the case because your files don't contain any `NSLocalizedString` entries. I'm not sure why this is an `Error!`, maybe we should change it to `Warning!` but in any case this is not a problem. Actually the command line should return `status ok` as you can see in [this line](https://github.com/Flinesoft/BartyCrouch/blob/5b18d9de2c8c030f9cea201a72073ab17bcea44a/Sources/Code/CommandLineActor.swift#L175).

**Comment by fadizant** [comment]
[Test.zip](https://github.com/Flinesoft/BartyCrouch/files/1804376/Test.zip)

Can you tell me what I missing in my demo 
I but my localization string files in folder Localizable inside my project folder and user this script in Xcode 

`bartycrouch code -p "$PROJECT_DIR/$PROJECT_NAME/Localizable" -l "$PROJECT_DIR/$PROJECT_NAME/Localizable" -a -s`

Thanks.

**Comment by Dschee** [comment]
@fadizant Thank you for the demo project. The script you are using is not setup correctly. According to the docs the `-p` (or `--path`) option is to set as follows:

> Set the base path to recursively search within for code files (.h, .m, .mm, .swift).

Since you are setting this to the `Localizable` folder, BartyCrouch doesn't find any code files from which it can extract Localizations. Instead just remove the `/Localizable` from the `-p` option like this:

``` bash
bartycrouch code -p "$PROJECT_DIR/$PROJECT_NAME" -l "$PROJECT_DIR/$PROJECT_NAME/Localizable" -a -s
```

Then it should work.

**Comment by fadizant** [comment]
Thanks for your help 👍
