### ISSUE TITLE
Base language detection

### ISSUE THREAD

**Issue by AlmightyCZ** [Flinesoft/BartyCrouch#91]
I have a project, with following language-related properties in project.pbxproj
`developmentRegion = English;`
`knownRegions = (				en,				Base,				sk,				cs,
			);` 
Also the Info.plist has `<key>CFBundleDevelopmentRegion</key>` set to `<string>en</string>`.
All the designer files (storyboard, views etc.) are designed in English.

Whenever I run `bartycrouch interfaces -p "."` in the project root folder, I get all the *.strings files updated, however all the strings from the designer files are written into files in the cs.lproj folder (where the Czech language is supposed to be) instead of the en.proj folder. 

Is there something wrong with my project? Or is there a way (parameter?) to specify my base language for bartycrouch?

Thank you

**Comment by Dschee** [comment]
Oh hey, sorry, I missed the email of your initial comment. :-/

I'm not sure if I understand what your problem is. So you have Storyboards with the languages `en`, `Base`, `sk` and `cs` but everything is put into the `cs.lproj` folder? That shouldn't happen. Are you sure you have a `Base` and the `Base` is a Storyboard file and all other languages are `.strings` files? Cause the only reason I can think of that everything is placed into `cs.lproj` folder is that something went wrong and BartyCrouch automatically uses the first language it can find in alphabetical order.

In general, you don't have to specify the base language, cause Interface Builder files will only work with BartyCrouch if they have [Base Internationalization](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/InternationalizingYourUserInterface/InternationalizingYourUserInterface.html#//apple_ref/doc/uid/10000171i-CH3-SW4) enabled.

If your problem still consists, I'd need an example project to investigate this further. You can upload one on GitHub if licensing isn't a problem or you can reproduce the issue in a demo app. Or in case it's a private project, feel free to send me an email to `github [at] cihatguenduez.de` and I'll keep the project secret.

**Comment by AlmightyCZ** [comment]
I sent you an email with the project and description.

Just to keep this issue up to date for future visitors.
Situation is this: `Base` folder contains storyboard and xib files. `en`, `cs` and `s`k folders contain string files. Where files en folder contain same strings as the storyboard and xib files.
When I make a change in storyboard and run BartyCrouch the following happens. Files in `en` and `sk` are updated as expected. However all the files in `cs` folder are updated and they are identical with the files in `en` folder. (Czech translation is completely rewritten to English one.) The last part of course happens even if there is no change made.

**Comment by AlmightyCZ** [comment]
Just a little bump :) Were you able to open stripped down version of my project?

**Comment by Dschee** [comment]
Funny that you're writing right now, cause I was just searching for your mail and couldn't find it. Could your resend it, maybe? Sorry for letting you wait and thanks!

**Comment by AlmightyCZ** [comment]
I just resent it, did you get it?

**Comment by Dschee** [comment]
Nope, I didn‘t get anything ...

**Comment by AlmightyCZ** [comment]
Don't know what's wrong, copied your email address and "replaced" the "at", I'm sending it from gmail.
Anyway here's dropbox link [https://www.dropbox.com/s/3vhqnziws3nhogj/Export.7z?dl=0] let me know, when you download it. Thank you

**Comment by Dschee** [comment]
Thanks I downloaded it.

**Comment by Dschee** [comment]
I found the problem. It's actually a feature so I'm not sure what to do about it, but let me explain it first.

## Problem explanation

Here's an extract of the changes happening in `cs.lproj` when BartyCrouch runs in your project:
<img width="533" alt="bildschirmfoto 2018-05-11 um 14 48 07" src="https://user-images.githubusercontent.com/6942160/39925048-7cd4cf16-552a-11e8-920b-77aaf340eff9.png">

Let's also have a look at the same entry in the language `sk.lproj`:
<img width="522" alt="bildschirmfoto 2018-05-11 um 14 50 59" src="https://user-images.githubusercontent.com/6942160/39925146-d3dc8056-552a-11e8-8705-6b86732ae599.png">

At first sight one might think, why is BartyCrouch replacing the correct Czech translation with the English one? And why isn't it doing so in the Slovak language?

Here's what's happening: If you take a look at the comment, you'll notice that it's the same for both languages. As a matter of fact, when creating the Strings files the first time in Xcode, Xcode will automatically take the values from the XIB or Storyboard and put them into the comments. It will also never change the comment value, even if you make changes in the XIB or Storyboard file, leaving you to have three different values for every entry: The actual value, the comment value and the XIB/Storyboard value. At the beginning the latter two are the same, but since Xcode doesn't update them, they tend to be different over time.

Since we can see that in the comment the value is of Czech language, I can assume that at the time where you first let Xcode generate the Strings files, your XIB or Storyboard had values in Czech language. It seems you later have changed this and made every value within the XIB or Storyboard be of English language. BartyCrouch has a feature built-in that will automatically update the comment value for you. So that's why we are seeing a change in the comment line for both example languages above. An additional feature of BartyCrouch is to – in case the comment value matches the real value exactly – to also update the real value. Since the actual value of the Czech translation is the same as the comment value, this is what happened here and what made BartyCrouch also update the value and replace it with the new English value which it found in the XIB or Storyboard file.

## Solution

Now that we know what the problem is, let's examine what can be done to solve this problem and/or to prevent it in the future:

1. To prevent this issue from happening again is to use English (or whatever language) in the XIB or Storyboard file from the beginning and never changing the language.
2. When the language is changed though, one manual way to fix it is to update the comment values to the new language manually. For example:

```
/* Class = "UILabel"; text = "Proveďte synchronizaci."; ObjectID = "RvR-Nz-aYE"; */
```
would need to be manually changed to
```
/* Class = "UILabel"; text = "Sync to get data."; ObjectID = "RvR-Nz-aYE"; */
```
3. Alternatively, you can also let BartyCrouch do its work and revert the wrong changes manually once. From then on (as long as you don't change the language again) the issue shouldn't happen again. This is the way I recommend you to fix this issue – with the help of a Git GUI tool (like [SourceTree](https://www.sourcetreeapp.com)) this shouldn't be a problem.

**Comment by AlmightyCZ** [comment]
Perfect! Thanks a lot :) I manually fixed the "wrong" changes as you suggested and it works now as expected. And yes, long time ago was the project czech-only.

**Comment by Dschee** [comment]
Glad I could help! 😊
